# ...existing code...
name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate deployment package
        run: zip -r frontend-app.zip . -x "*.git*" -x "*.github*" -x "*.vscode*" -x "*node_modules*" -x "*tests*" -x "*.env*"

      - name: Get Node.js version
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> $GITHUB_ENV
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ env.VERSION }}
          region: ap-southeast-1
          deployment_package: frontend-app.zip
